version: '2'
services:
    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jarvis
            MYSQL_USER: root
            MYSQL_PASSWORD: root