# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#

services:
    app.select_extension:
        class: AppBundle\Form\Extension\Select
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }
    title.manager:
        class: AppBundle\Manager\TitleManager
        arguments: ['@doctrine.orm.entity_manager']
    contact.manager:
        class: AppBundle\Manager\ContactManager
        arguments: ['@doctrine.orm.entity_manager']
    file.manager:
        class: AppBundle\Manager\FileManager
        arguments: ['@doctrine.orm.entity_manager']
    file.business:
        class: AppBundle\Business\FileBusiness
        arguments: ['@file.manager']
    folder.manager:
        class: AppBundle\Manager\FolderManager
        arguments: ['@doctrine.orm.entity_manager']
    folder.business:
        class: AppBundle\Business\FolderBusiness
        arguments: ['@folder.manager']